// Regenerates the embedded item/gem databases inside GemOptimizer.html from the WowSims MoP db.
// Usage: node build_data.js [path-to-db.json]   (downloads from GitHub if no path given)
// Source: https://raw.githubusercontent.com/wowsims/mop/master/assets/database/db.json
const fs=require('fs'),path=require('path');

const STAT_KEYS={0:'str',1:'agi',2:'sta',3:'int',4:'spi',5:'hit',6:'crit',7:'haste',8:'exp',
  9:'dodge',10:'parry',11:'mastery',15:'resil',16:'pvppower'};
const COLOR_NAMES={1:'meta',2:'red',3:'blue',4:'yellow',5:'green',6:'orange',7:'purple',8:'prismatic',9:'cogwheel',10:'sha'};

async function main(){
  let raw;
  if(process.argv[2]){
    raw=fs.readFileSync(process.argv[2],'utf8');
  }else{
    const resp=await fetch('https://raw.githubusercontent.com/wowsims/mop/master/assets/database/db.json');
    if(!resp.ok)throw new Error('download failed: '+resp.status);
    raw=await resp.text();
  }
  const db=JSON.parse(raw);

  // Items with sockets: [id, [socketColorNames], bonusStatKey|0, bonusAmt, typeId, name]
  const items=db.items.filter(i=>i.gemSockets&&i.gemSockets.length).map(i=>{
    const sb=i.socketBonus||[];
    const si=sb.findIndex(v=>v>0);
    const bKey=si>=0?(STAT_KEYS[si]||0):0;
    return [i.id,i.gemSockets.map(c=>COLOR_NAMES[c]||'unknown'),bKey||0,bKey?sb[si]:0,i.type||0,i.name||''];
  });

  // All gems: [id, colorName, {statKey:amt}, name]
  const gems=db.gems.map(g=>{
    const s={};
    (g.stats||[]).forEach((v,ix)=>{if(v&&STAT_KEYS[ix])s[STAT_KEYS[ix]]=v;});
    return [g.id,COLOR_NAMES[g.color]||'unknown',s,g.name||''];
  });

  const block=
`// --- generated by build_data.js from wowsims/mop db.json — do not hand-edit ---
const ITEM_DB=${JSON.stringify(items)};
const GEM_DB=${JSON.stringify(gems)};
// --- end generated ---`;

  const htmlPath=path.join(__dirname,'GemOptimizer.html');
  const html=fs.readFileSync(htmlPath,'utf8');
  const re=/\/\/ --- generated by build_data\.js[\s\S]*?\/\/ --- end generated ---/;
  if(!re.test(html))throw new Error('generated-data markers not found in GemOptimizer.html');
  fs.writeFileSync(htmlPath,html.replace(re,block));
  console.log(`embedded ${items.length} items (${(JSON.stringify(items).length/1024).toFixed(0)} KB) and ${gems.length} gems (${(JSON.stringify(gems).length/1024).toFixed(0)} KB)`);
}
main().catch(e=>{console.error(e);process.exit(1);});
